JWAnket/Controllers/SurveyController.cs
using System.Collections.Generic;
using System.Data.SQLite;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using JWAnket.Models;

namespace JWAnket.Controllers
{
    public class SurveyController : Controller
    {
        public ActionResult BeginSurvey()
        {
            return View();
        }

        //Mentoring Öncesi
        public ActionResult BeforeSurvey()
        {
            return View();
        }

        public ActionResult FirstPage()
        {
            SurveyModel currentModel = new SurveyModel
            {
                WhiskeyBrandList = new List<CheckBoxList>
                {
                    new CheckBoxList {Id = 1, Name = "JW Red Label"},
                    new CheckBoxList {Id = 2, Name = "JW Black Label"},
                    new CheckBoxList {Id = 3, Name = "JW Double Black Label"},
                    new CheckBoxList {Id = 4, Name = "Jack Daniels"},
                    new CheckBoxList {Id = 5, Name = "Chivas 12"},
                    new CheckBoxList {Id = 6, Name = "Chivas 18"},
                    new CheckBoxList {Id = 7, Name = "Dimple Golden Selection"},
                    new CheckBoxList {Id = 8, Name = "JW Gold Label"},
                    new CheckBoxList {Id = 9, Name = "JW Platinum Label"},
                    new CheckBoxList {Id = 10, Name = "JW Blue Label"},
                    new CheckBoxList {Id = 11, Name = "Cardhu"},
                    new CheckBoxList {Id = 12, Name = "Glenkinchie"},
                    new CheckBoxList {Id = 13, Name = "Talisker"},
                    new CheckBoxList {Id = 14, Name = "Lagavulin"},
                    new CheckBoxList {Id = 15, Name = "Singleton 12"},
                    new CheckBoxList {Id = 16, Name = "Singleton 15"},
                    new CheckBoxList {Id = 17, Name = "Jim Beam"},
                    new CheckBoxList {Id = 18, Name = "Ballantines"},
                    new CheckBoxList {Id = 19, Name = "Glenlivet "},
                    new CheckBoxList {Id = 20, Name = "Mac Allen"},
                    new CheckBoxList {Id = 21, Name = "Jameson"},
                    new CheckBoxList {Id = 22, Name = "Glenfiddich"},
                    new CheckBoxList {Id = 23, Name = "Bush Mils"},
                    new CheckBoxList {Id = 24, Name = "Viski İçmiyorum"}
                }
            };

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult SecondPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.ReasonList = new List<CheckBoxList>
            {
                new CheckBoxList {Id = 1, Name = "Viskinin Türü (Scotch, Tennessee, Bourbon vb.)"},
                new CheckBoxList {Id = 2, Name = "Tat"},
                new CheckBoxList {Id = 3, Name = "Alışkanlık"},
                new CheckBoxList {Id = 4, Name = "Fiyat"},
                new CheckBoxList {Id = 5, Name = "Ambalaj - Şişe"},
                new CheckBoxList {Id = 6, Name = "Arkadaşlarımın İçtiği Marka"}
            };

            currentModel.WhiskeyBrandList = surveyModel.WhiskeyBrandList;
            currentModel.OtherWhiskeyBrandText = surveyModel.OtherWhiskeyBrandText;

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult ThirdPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.OtherWhiskeyBrandList = new List<CheckBoxList>
            {
                new CheckBoxList {Id = 1, Name = "JW Red Label"},
                new CheckBoxList {Id = 2, Name = "JW Black Label"},
                new CheckBoxList {Id = 3, Name = "JW Double Black Label"},
                new CheckBoxList {Id = 4, Name = "Jack Daniels"},
                new CheckBoxList {Id = 5, Name = "Chivas 12"},
                new CheckBoxList {Id = 6, Name = "Chivas 18"},
                new CheckBoxList {Id = 7, Name = "Dimple Golden Selection"},
                new CheckBoxList {Id = 8, Name = "JW Gold Label"},
                new CheckBoxList {Id = 9, Name = "JW Platinum Label"},
                new CheckBoxList {Id = 10, Name = "JW Blue Label"},
                new CheckBoxList {Id = 11, Name = "Cardhu"},
                new CheckBoxList {Id = 12, Name = "Glenkinchie"},
                new CheckBoxList {Id = 13, Name = "Talisker"},
                new CheckBoxList {Id = 14, Name = "Lagavulin"},
                new CheckBoxList {Id = 15, Name = "Singleton 12"},
                new CheckBoxList {Id = 16, Name = "Singleton 15"},
                new CheckBoxList {Id = 17, Name = "Jim Beam"},
                new CheckBoxList {Id = 18, Name = "Ballantines"},
                new CheckBoxList {Id = 19, Name = "Glenlivet "},
                new CheckBoxList {Id = 20, Name = "Mac Allen"},
                new CheckBoxList {Id = 21, Name = "Jameson"},
                new CheckBoxList {Id = 22, Name = "Glenfiddich"},
                new CheckBoxList {Id = 23, Name = "Bush Mils"},
                new CheckBoxList {Id = 24, Name = "Viski İçmiyorum"}
            };

            currentModel.OtherReasonText = surveyModel.OtherReasonText;
            currentModel.ReasonList = surveyModel.ReasonList;

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        //Mentoring Sonrası
        [HttpPost]
        public ActionResult AfterSurvey(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.OtherWhiskeyBrandList = surveyModel.OtherWhiskeyBrandList;
            currentModel.YetAnotherWhiskeyBrandText = surveyModel.YetAnotherWhiskeyBrandText;

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult FourthPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.ChangedWhiskeyBrandList = new List<CheckBoxList>
            {
                new CheckBoxList {Id = 1, Name = "JW Red Label"},
                new CheckBoxList {Id = 2, Name = "JW Black Label"},
                new CheckBoxList {Id = 3, Name = "JW Double Black Label"},
                new CheckBoxList {Id = 4, Name = "Jack Daniels"},
                new CheckBoxList {Id = 5, Name = "Chivas 12"},
                new CheckBoxList {Id = 6, Name = "Chivas 18"},
                new CheckBoxList {Id = 7, Name = "Dimple Golden Selection"},
                new CheckBoxList {Id = 8, Name = "JW Gold Label"},
                new CheckBoxList {Id = 9, Name = "JW Platinum Label"},
                new CheckBoxList {Id = 10, Name = "JW Blue Label"},
                new CheckBoxList {Id = 11, Name = "Cardhu"},
                new CheckBoxList {Id = 12, Name = "Glenkinchie"},
                new CheckBoxList {Id = 13, Name = "Talisker"},
                new CheckBoxList {Id = 14, Name = "Lagavulin"},
                new CheckBoxList {Id = 15, Name = "Singleton 12"},
                new CheckBoxList {Id = 16, Name = "Singleton 15"},
                new CheckBoxList {Id = 17, Name = "Jim Beam"},
                new CheckBoxList {Id = 18, Name = "Ballantines"},
                new CheckBoxList {Id = 19, Name = "Glenlivet "},
                new CheckBoxList {Id = 20, Name = "Mac Allen"},
                new CheckBoxList {Id = 21, Name = "Jameson"},
                new CheckBoxList {Id = 22, Name = "Glenfiddich"},
                new CheckBoxList {Id = 23, Name = "Bush Mils"},
                new CheckBoxList {Id = 24, Name = "Viski İçmiyorum"}
            };

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult FifthPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.ChangedWhiskeyBrandList = surveyModel.ChangedWhiskeyBrandList;
            currentModel.ChangedWhiskeyBrandText = surveyModel.ChangedWhiskeyBrandText;

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult SixthPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.NameSurname = surveyModel.NameSurname;
            currentModel.Phone = surveyModel.Phone;
            currentModel.EMail = surveyModel.EMail;

            Session["SurveyModel"] = currentModel;

            return View(currentModel);
        }

        [HttpPost]
        public ActionResult FinalPage(SurveyModel surveyModel)
        {
            SurveyModel currentModel = (SurveyModel)Session["SurveyModel"];

            currentModel.Comments = surveyModel.Comments;

            PersistModel(currentModel);

            return View();
        }

        private void PersistModel(SurveyModel currentModel)
        {
            string databasePath = Server.MapPath("~/Content/survey.sqlite");
            SQLiteConnection conn = new SQLiteConnection(@"Data Source=" + databasePath + ";Version=3;");

            try
            {
                SQLiteCommand cmd = new SQLiteCommand();
                cmd.Connection = conn;
                conn.Open();

                cmd.CommandText =
                    "INSERT INTO JwSurvey(CreateDate, Comments) VALUES(@CreateDate, @Comments); select last_insert_rowid();";
                cmd.Parameters.AddWithValue("CreateDate", currentModel.CreateDate);
                cmd.Parameters.AddWithValue("Comments", currentModel.Comments);

                int surveyId = int.Parse(cmd.ExecuteScalar().ToString());

JWAnket/Views/Survey/AfterSurvey.cshtml
<!DOCTYPE html>
<html lang="en" class="after-survey-body">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anket Sonrası</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-xs-12 text-center bottomaligned">
            @using (Html.BeginForm("FourthPage", "Survey"))
            {
                <input type="submit" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
            }
        </div>
    </div>
</body>
</html>

JWAnket/Views/Survey/BeforeSurvey.cshtml
<!DOCTYPE html>
<html lang="en" class="before-survey-body">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anket Öncesi</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-xs-12 text-center bottomaligned">
            @using (Html.BeginForm("FirstPage", "Survey"))
            {
                <input type="submit" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
            }
        </div>
    </div>
</body>
</html>

JWAnket/Views/Survey/BeginSurvey.cshtml
<!DOCTYPE html>
<html lang="en" class="begin-survey-body">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anket Giriş</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-xs-12 text-center bottomaligned">
            @using (Html.BeginForm("BeforeSurvey", "Survey"))
            {
                <input type="submit" value="ANKETE BAŞLA" class="btn btn-default" style="margin-bottom: 50px;" />
            }
        </div>
    </div>
</body>
</html>

JWAnket/Views/Survey/FifthPage.cshtml
@model JWAnket.Models.SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body class="fifth-page-body">
    @using (Html.BeginForm("SixthPage", "Survey"))
    {
        <div class="col-xs-12 text-center topalignedmentoring">
            <div class="row">
                <div>
                    @Html.TextBoxFor(m => Model.NameSurname, new { @placeholder = "İsim Soyisim" })
                </div>
            </div>
            <div class="row">
                <div>
                    @Html.TextBoxFor(m => Model.Phone, new { @placeholder = "Telefon" })
                </div>
            </div>
            <div class="row">
                <div>
                    @Html.TextBoxFor(m => Model.EMail, new { @placeholder = "E-Mail" })
                </div>
            </div>
            <div class="col-xs-12 text-center">
                <input type="submit" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
            </div>
        </div>
    }
</body>
</html>

JWAnket/Views/Survey/FinalPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body class="final-page-body">
</body>
</html>

JWAnket/Views/Survey/FirstPage.cshtml
@using JWAnket.Models
@model SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/scroll.js"></script>
    <script src="~/Scripts/validatecheckbox.js"></script>

</head>
<body class="first-page-body">
    @using (Html.BeginForm("SecondPage", "Survey", FormMethod.Post, new { surveyModel = Model }))
    {
        <div class="col-xs-12 text-center topaligned">
            <span id="validationMessage" style="color: white"></span>
            <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-8">
                    <div id="upArrow" class="fontyellow">▲</div>
                    <div class="cover" style="margin: 0 auto; height: 196px; border: solid 2px #9a9a9a; overflow-y: scroll;">
                        <table style="width: 100%">
                            @for (int i = 0; i < Model.WhiskeyBrandList.Count; i++)
                            {
                                <tr>
                                    <td class="fontyellow">@Html.LabelFor(m => Model.WhiskeyBrandList[i].IsSelected, Model.WhiskeyBrandList[i].Name)</td>
                                    <td></td>
                                    <td>
                                        @Html.HiddenFor(m => Model.WhiskeyBrandList[i].Id)
                                        @Html.HiddenFor(m => Model.WhiskeyBrandList[i].Name)
                                        @Html.CheckBoxFor(m => Model.WhiskeyBrandList[i].IsSelected)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div id="downArrow" class="fontyellow">▼</div>
                </div>
                <div class="col-xs-2"></div>
            </div>
            <div class="row">
                <div>
                    @Html.TextAreaFor(m => Model.OtherWhiskeyBrandText, new { @placeholder = "Diğer" })
                </div>

                <div>
                    <input type="submit" onclick="return submitWith();" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
                </div>
            </div>
        </div>
    }
</body>
</html>

JWAnket/Views/Survey/FourthPage.cshtml
@model JWAnket.Models.SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/scroll.js"></script>
    <script src="~/Scripts/validatecheckbox.js"></script>
</head>

<body class="fourth-page-body">
    @using (Html.BeginForm("FifthPage", "Survey", FormMethod.Post, new { surveyModel = Model }))
    {
        <div class="col-xs-12 text-center topaligned">
            <span id="validationMessage" style="color: white"></span>
            <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-8">
                    <div id="upArrow" class="fontyellow">▲</div>
                    <div class="cover" style="margin: 0 auto; height: 196px; border: solid 2px #9a9a9a; overflow-y: scroll;">
                        <table style="width: 100%">
                            @for (int i = 0; i < Model.ChangedWhiskeyBrandList.Count; i++)
                            {
                                <tr>
                                    <td class="fontyellow">@Html.LabelFor(m => Model.ChangedWhiskeyBrandList[i].IsSelected, Model.ChangedWhiskeyBrandList[i].Name)</td>
                                    <td></td>
                                    <td>
                                        @Html.HiddenFor(m => Model.ChangedWhiskeyBrandList[i].Id)
                                        @Html.HiddenFor(m => Model.ChangedWhiskeyBrandList[i].Name)
                                        @Html.CheckBoxFor(m => Model.ChangedWhiskeyBrandList[i].IsSelected)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div id="downArrow" class="fontyellow">▼</div>
                </div>
                <div class="col-xs-2"></div>
            </div>
            <div class="row">
                <div>
                    @Html.TextAreaFor(m => Model.ChangedWhiskeyBrandText, new {@placeholder = "Diğer"})
                </div>
                <div>
                    <input type="submit" onclick="return submitWith();" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;"/>
                </div>
            </div>
        </div>
    }
</body>
</html>

JWAnket/Views/Survey/SecondPage.cshtml
@model JWAnket.Models.SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/validatecheckbox.js"></script>
</head>
<body class="second-page-body">
    @using (Html.BeginForm("ThirdPage", "Survey", FormMethod.Post, new { surveyModel = Model }))
    {
        <div class="col-xs-12 text-center topaligned">
            <span id="validationMessage" style="color: white"></span>
            <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-8">
                    <div class="cover" style="margin: 0 auto; height: 196px; border: solid 2px #9a9a9a; overflow-y: scroll;">
                        <table style="width: 100%">
                            @for (int i = 0; i < Model.ReasonList.Count; i++)
                            {
                                <tr>
                                    <td class="fontyellow">@Html.LabelFor(m => Model.ReasonList[i].IsSelected, @Model.ReasonList[i].Name)</td>
                                    <td></td>
                                    <td>
                                        @Html.HiddenFor(m => Model.ReasonList[i].Id)
                                        @Html.HiddenFor(m => Model.ReasonList[i].Name)
                                        @Html.CheckBoxFor(m => Model.ReasonList[i].IsSelected)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
                <div class="col-xs-2"></div>
            </div>
            <div class="row">
                <div>
                    @Html.TextAreaFor(m => Model.OtherReasonText, new { @placeholder = "Diğer" })
                </div>
                <div>
                    <input type="submit" onclick="return submitWith();" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
                </div>
            </div>
        </div>
    }
</body>
</html>

JWAnket/Views/Survey/SixthPage.cshtml
@model JWAnket.Models.SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body class="sixth-page-body">
    @using (Html.BeginForm("FinalPage", "Survey"))
    {
        <div class="col-xs-12 text-center topalignedfifthpage">
            <div class="row">
                <div>
                    @Html.TextAreaFor(m => Model.Comments, new { @placeholder = "Yorum" })
                </div>
                <div>
                    <input type="submit" value="Anketi Bitir" class="btn btn-default" style="margin-bottom: 50px;" />
                </div>
            </div>
        </div>
    }
</body>
</html>

JWAnket/Views/Survey/ThirdPage.cshtml
@model JWAnket.Models.SurveyModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/scroll.js"></script>
    <script src="~/Scripts/validatecheckbox.js"></script>
</head>

<body class="third-page-body">
    @using (Html.BeginForm("AfterSurvey", "Survey", FormMethod.Post, new { surveyModel = Model }))
    {
        <div class="col-xs-12 text-center topaligned">
            <span id="validationMessage" style="color: white"></span>
            <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-8">
                    <div id="upArrow" class="fontyellow">▲</div>
                    <div class="cover" style="margin: 0 auto; height: 196px; border: solid 2px #9a9a9a; overflow-y: scroll;">
                        <table style="width: 100%">
                            @for (int i = 0; i < Model.OtherWhiskeyBrandList.Count; i++)
                            {
                                <tr>
                                    <td class="fontyellow">@Html.LabelFor(m => Model.OtherWhiskeyBrandList[i].IsSelected, Model.OtherWhiskeyBrandList[i].Name)</td>
                                    <td></td>
                                    <td>
                                        @Html.HiddenFor(m => Model.OtherWhiskeyBrandList[i].Id)
                                        @Html.HiddenFor(m => Model.OtherWhiskeyBrandList[i].Name)
                                        @Html.CheckBoxFor(m => Model.OtherWhiskeyBrandList[i].IsSelected)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div id="downArrow" class="fontyellow">▼</div>
                </div>
                <div class="col-xs-2"></div>
            </div>
            <div class="row">
                <div>
                    @Html.TextAreaFor(m => Model.YetAnotherWhiskeyBrandText, new { @placeholder = "Diğer" })
                </div>
                <div>
                    <input type="submit" onclick="return submitWith();" value="Sonraki Sayfa" class="btn btn-default" style="margin-bottom: 50px;" />
                </div>
            </div>
        </div>
    }
</body>
</html>